name = "SimpleDiscontinuousGalerkin"
uuid = "1c8e7e25-3265-4959-9fcf-9ce6764f3290"
authors = ["Joshua Lampert <joshua.lampert@uni-hamburg.de> and contributors"]
version = "0.1.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SummationByPartsOperators = "9f78cca6-572e-554e-b819-917d2f1cf240"

[compat]
LinearAlgebra = "1"
Reexport = "1.2"
SummationByPartsOperators = "0.5.78"
julia = "1.10"
